### ISSUE TITLE
Implement comment parsing

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#10]
Currently, the assembler does not support comments in the source code. We should implement parsing of comments according to the spec described [here](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA#Comments).

**Comment by diegomrsantos** [comment]
Is doing one pass just to remove the comments an acceptable way of implementing this?

**Comment by grjte** [comment]
Just to clarify - comments be anywhere, right? Including within procedures, and outside of both procedures and scripts?

**Comment by bobbinth** [comment]
> Just to clarify - comments be anywhere, right? Including within procedures, and outside of both procedures and scripts?

Yes - this is correct. But the nice thing of handling at the `TokenStream` level is that tokens are iterated over before we need to worry about procedures, scripts etc.

**Comment by bobbinth** [comment]
Closed by #20
