### ISSUE TITLE
Single-element memory operations

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#102]
Current [assembly instructions](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA#Random-access-memory) for memory access deal with words (4 field elements). This creates quite a bit of over head for use case when we want to read/write a single field element. The overhead is in both places: the VM itself and the assembly instruction sequences needed to accomplish single-element reads/writes.

Adding dedicated operations to read/write single elements at the VM level is possible, but we should probably do it at a later date, once we have a better picture of how frequently these operations are used. However, we could add instructions at the assembly level to help with this. The instructions I'm thinking of are:

* `push.mem.addr` - pushes the first element of the word at *addr* onto the stack.
* `push.local.idx` - same as above but for a local.
* `pop.mem.addr`- pops the element off the stack and saves it *addr*.
* `pop.local.idx`- same as above but for a local.

**Comment by grjte** [comment]
> Adding dedicated operations to read/write single elements at the VM level is possible, but we should probably do it at a later date, once we have a better picture of how frequently these operations are used. 

Yeah, I think it makes sense to hold off on this.

> However, we could add instructions at the assembly level to help with this.

Sounds good. Do we also want to allow passing the address via the stack for the ```mem``` operations like we do when dealing with words?

**Comment by bobbinth** [comment]
> Do we also want to allow passing the address via the stack for the `mem` operations like we do when dealing with words?

Yes, I think it would make sense to do that.

**Comment by grjte** [comment]
Great, I'll take a look as I finish the rest of the io ```push``` refactor

**Comment by bobbinth** [comment]
Sounds good! I've updated the [sepcs](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA?both#Random-access-memory) to include these new instructions.

**Comment by bobbinth** [comment]
Closed by #110
