### ISSUE TITLE
Instruction for computing absolute address of a local variable

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#105]
In some situations it may be useful to get the absolute memory location of a local variable.

For example, let's say we have a procedure for multiplying two 256-bit integers (`u256:mul`) this procedure expects memory addresses of operands `a` and `b` to be on the top of the stack, and after it performs the multiplication, it will leave the result on the top of the stack (we could have passed operands `a` and `b` via the stack as well, but for the purpose of this example, we do it via memory).

Thus, to invoke `u256:uml` the caller needs to put absolute addresses of `a` and `b` onto the stack, but if `a` and `b` "live" in local memory of the caller, it is not clear how to do that (since we don't have an instruction for accessing the value of `fmp` directly).

We could add assembly instructions to access `fmp` and then the caller would be able to compute the absolute address, but i wonder whether having a more specialized instruction is more convenient. I'm thinking of something like this (though open to other name/format suggestions):

```
push.env.locaddr.i
```
where *i* is the index of the local. This instruction would read the `fmp`, subtract *i* from it, and push the result onto the stack.

The only downside of this I can think of is that it would enable potential abuse of `fmp` where a procedure could return absolute address of its local (which would be a logical error).

**Comment by grjte** [comment]
> The only downside of this I can think of is that it would enable potential abuse of fmp where a procedure could return absolute address of its local (which would be a logical error).

Just to reiterate - procedures will always be trusted, right? (With functions used for "untrusted" procedures, where parameters passed via the stack, as discussed in #73 )

> We could add assembly instructions to access fmp and then the caller would be able to compute the absolute address, but i wonder whether having a more specialized instruction is more convenient. 

Yes, I prefer passing via env as proposed rather than requiring the caller to figure it out themselves. The complexity is minimized this way & kept in one place (where it will in fact be straightforward to handle).

> In some situations it may be useful to get the absolute memory location of a local variable.
 
How much do you expect this to come up, though? I wonder if it's worth doing it now vs. waiting to see to what extent we really want this & in what contexts, since different contexts could drive different preferred solutions

**Comment by bobbinth** [comment]
> Just to reiterate - procedures will always be trusted, right?

Yes, this is correct.

> How much do you expect this to come up, though?  I wonder if it's worth doing it now vs. waiting to see to what extent we really want this & in what contexts, since different contexts could drive different preferred solutions.

Good point! We can wait a little on this. I think u256 operations, EC signatures, and hash functions might need something like this - but good to wait until we actually start working on them.

**Comment by bobbinth** [comment]
Closed by #124
