### ISSUE TITLE
Optimize the logic for inlining procedures

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#109]
The way procedures are parsed and inlined causes extra ```noop``` operations to be added and can be optimized.

As noted in the [specs](https://hackmd.io/yr-ieh7SSKOzWw7Kdo9gnA), the rules for grouping operations inside of span blocks are:
- the maximum number of operations per group is 9 (since a group is represented by a single 64-bit field element and each opcode is encoded with 7 bits)
- the first group of a batch can start with any operation
- for all other groups in a batch (groups 2-8), an operation carrying an immediate value (e.g. ```push.2```) cannot be the first operation in the group. In this case, the VM must insert a ```noop``` in front of it.

Currently, it seems that ```noop``` insertion is done during procedure parsing and then again during procedure inlining, causing extra unnecessary ```noop``` instructions to be added.

Here are some (very contrived) examples to demonstrate:

## Example - Procedure Without Locals

Assembly:
```
    proc.foo
        push.0 push.0 push.0 push.0
        drop drop drop drop
        push.3 push.7 mul
    end
    begin
        push.2 push.3 add
        exec.foo
    end
```

Compiled:
```
    begin
        span
            push(2) push(3) add
            pad pad pad pad
            drop drop drop drop
            push(3) noop push(7) mul
        end
    end
```

The ```noop``` is added during the parsing of the procedure where ```push(7)``` would be the 10th instruction and would therefore be the first instruction in a group. However, once the procedure is inlined, this ```noop``` is no longer necessary, because at this point the second group starts with ```drop```. The batches in the compiled script seem to regroup the operations correctly such that the ```push(3)``` and ```push(7)``` from the procedure are no longer in different groups, as seen here:

Op Batches:
```
op_batches: [
        OpBatch { 
          ops: 
            [Push(BaseElement(2)), Push(BaseElement(3)), Add, Pad, Pad, Pad, Pad, Drop, Drop, Drop, Drop, Push(BaseElement(3)), Noop, Push(BaseElement(7)), Mul], 
          groups: 
            [BaseElement(1016745240677138690), BaseElement(2), BaseElement(3), BaseElement(241055074062), BaseElement(3), BaseElement(7), BaseElement(0), BaseElement(0)] 
        }]
```

## Example - Procedure With Locals

Assembly:
```
        proc.foo.3 
            push.0 push.1 
            storew.local.2 
            add 
            push.0 
            loadw.local.2 
            mul 
            push.0 push.0 push.0 drop drop 
        end 
        begin 
            push.4 push.3 push.2 push.1 
            exec.foo 
        end
```

Compiled:
```
        begin 
            span 
                push(4) push(3) push(2) pad incr 
                push(3) fmpupdate 
                pad pad incr 
                push(2) neg fmpadd storew 
                add 
                pad 
                noop push(2) neg fmpadd loadw 
                mul 
                pad pad pad drop drop 
                noop push(3) neg fmpupdate 
            end 
        end
```

In this example, the first ```noop``` is added on line 9 during procedure parsing where the 1st operation of the second group of the procedure operations is ```push(2)``` (the first VM instruction for ```loadw.local.2```). Once the procedure is inlined, the placement of this ```noop``` is no longer necessary. However, once all operations are combined, the second ```noop``` needs to be added, since, after the inlining, the ```push(2)``` on line 12 would be the first operation in a group. Notice that without the first unnecessary ```noop``` this second ```noop``` would not be required.

**Comment by bobbinth** [comment]
Another issue we need to consider during procedure inlining is procedures where the body of the procedure does not start/end with a Span block. For example, something like this:

```
    (root)
   /     \
(span) (group)
```
Here, the Span block (the left child) can be combined with the outer Span block (the one where `exec.<proc>` is defined) but the current logic will not do that.

**Comment by grjte** [comment]
This issue should be resolved by #212 , but it would be good to 1) confirm that it's resolved and 2) identify if any other similar suboptimal behaviour has been introduced or still exists.

**Comment by 0xKanekiKen** [comment]
@bobbinth @grjte: I can confirm this.

**Comment by 0xKanekiKen** [comment]
The issue I think has been resolved now. I don't see a NOOP when compiling a script in the assembly. For eg in the above cases I'm seeing the following outputs: 

<h2>Procedure without Locals</h2>

Assembly
```
        proc.foo.3 
            push.0 push.1 
            storew.local.2 
            add 
            push.0 
            loadw.local.2 
            mul 
            push.0 push.0 push.0 drop drop 
        end 
        begin 
            push.4 push.3 push.2 push.1 
            exec.foo 
        end
```
Compiled
```
        begin 
            span 
                push(2) push(3) add 
                pad pad pad pad 
                drop drop drop drop 
                push(3) push(7) mul 
            end 
        end
```
Op Batches: 
```
   OpBatch 
       ops:
           Push(BaseElement(2)), Push(BaseElement(3)), Add, Pad, Pad, Pad, Pad, Drop, Drop, Drop, Drop, Push(BaseElement(3)), Push(BaseElement(7)), Mul
       groups:
           BaseElement(944120264010105348), BaseElement(2), BaseElement(3), BaseElement(19872679565), BaseElement(3), BaseElement(7), BaseElement(0), BaseElement(0) 
       op_counts: [9, 0, 0, 5, 0, 0, 0, 0], 
       num_groups: 6   
```

<h2>Procedure without Locals</h2>
Assembly

```     
        proc.foo.3 
            push.0 push.1 
            storew.local.2 
            add 
            push.0 
            loadw.local.2 
            mul 
            push.0 push.0 push.0 drop drop 
        end 
        begin 
            push.4 push.3 push.2 push.1 
            exec.foo 
        end
```

Compiled
```
        begin 
            span 
                push(4) push(3) push(2) pad incr
                push(3) fmpupdate pad pad incr
                push(18446744069414584319) fmpadd storew 
                add pad pad pad pad drop drop 
                push(18446744069414584318) fmpupdate 
            end 
        end
```
Op Batches: 
```
    OpBatch 
       ops:
           Push(BaseElement(4)), Push(BaseElement(3)), Push(BaseElement(2)), Pad, Incr, Push(BaseElement(3)), FmpUpdate, Pad, Pad, Incr, Push(BaseElement(18446744069414584319)), FmpAdd, StoreW, Add, Pad, Push(BaseElement(18446744069414584319)), FmpAdd, LoadW
       groups:
           BaseElement(871459861915828740), BaseElement(4), BaseElement(3), BaseElement(2), BaseElement(3), BaseElement(3748138813820535305), BaseElement(18446744069414584319), BaseElement(18446744069414584319)
       op_counts: [9, 0, 0, 0, 0, 9, 0, 0], 
       num_groups: 8   

    OpBatch 
       ops:
           Mul, Pad, Pad, Pad, Drop, Drop, Push(BaseElement(18446744069414584318)), FmpUpdate
       groups:
           BaseElement(1706892237932106), BaseElement(18446744069414584318), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0)
       op_counts: [8, 0, 0, 0, 0, 0, 0, 0], 
       num_groups: 2
```

**Comment by bobbinth** [comment]
@0xKanekiKen - great! Thanks for checking!
