### ISSUE TITLE
Stacking of auxiliary traces

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#114]
The VM has several components traces of which should be "stacked" so that they all share the same set of execution trace columns. These components are:

* Hasher
* Bitwise processor
* Memory controller

All of these components already implement `fill_trace()` methods which should help with the process. The overall procedure for building a trace is as follows:

First, we need to determine overall length of the execution trace (this would happen when we convert `Process` struct into the `ExecutionTrace` [here](https://github.com/maticnetwork/miden/blob/next/processor/src/trace.rs#L19)). This length should be computed as be the max of the lengths of all segments of the trace. For the purposes of this issue, we care only about two segments: stack trace and auxiliary table trace.

Stack trace can be retrieved via `Stack::trace_length()` (which should probably be renamed into `trace_len()` for consistency). All components of the auxiliary table also expose `trace_len()`.  So, the length should be: `max(stack_len, hasher_len + bitwise_len + memory_len)`. And then we need to pad this length to the next power of two.

Once we have this length, we should allocate 18 vectors of this length, break it into fragments corresponding to lengths of each auxiliary component, and use `fill_trace()` to fill corresponding segment. We fill the fragments as follows:
1. First we fill the Hasher fragment. For this fragment values in column 0 are set to `ZERO`, and the remaining 17 columns contain the actual hasher trace.
2. Then we fill the Bitwsie fragment. For this fragment values in column 0 are set to `ONE` and values in column 1 are set to `ZERO`. The next 13 columns contain the actual bitwise processor trace. The remaining 3 columns are padded with `ZERO`
3. Then we fill the Memory fragment. For this fragment values in columns 0 and 1 are set to `ONE`, values in column 2 are set to `ZERO`. The next 14 columns contain the actual memory trace, and the last column is padded with `ZERO`.
4. If the above doesn't fill all the table completely, we need to pad the remaining rows. For padded rows values in the first 3 columns are set to `ONE`, and values in remaining columns are set to `ZERO`.

Even though the above is described sequentially - we can fill all fragments in parallel.

Also, the Bitwise trace is currently missing two columns (so, currently in the code the number of bitwise columns is 11 rather than 13). These are selector columns which we need to identify the bitwise operation being performed.

**Comment by grjte** [comment]
For reference, a diagram of the trace layout is ![here](https://user-images.githubusercontent.com/91497953/154024992-68748cec-f7a7-4d51-9936-ca39dab232a9.jpeg)

**Comment by bobbinth** [comment]
Closed by #122
