### ISSUE TITLE
Standard library v0.1 content

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#125]
Now that support for standard library imports has landed in #121 we should start discussing what we want to include into the initial release of `stdlib`. Here are my preliminary thoughts on the library content:

* `math`
  * `u64` - arithmetic and bitwise operations with 64-bit unsigned integers.
  * `u128` - not sure if we need this, maybe skip for v0.1?
  * `u256` - needed to support EVM. we should discuss if we want to try to support all operations in the original release.
* `crypto`
  * `hashes`
    * `blake3` - already being worked on in #77 
    * `sha256` - already being worked on in #123 
    * `Keccak256`- probably defer to future versions.
  * `sigs` (verification only)
    * `horst` - an instantiation of HORST signature scheme using default hash function of the VM. Could be a good way to test out `mtree.get` instruction.
    * `schnorr` - an instantiation of Schnorr signature using the default curve of the VM. Definitely delay till later.
* `evm` - EVM-specific built-ins not covered above. Probably defer to future releases.

Anything else I'm missing?

**Comment by grjte** [comment]
I would rather skip `u128` and aim for all `u256` operations.

**Comment by bobbinth** [comment]
Agree on skipping `u128`. Regarding `u256`, supporting everything would be quite difficult. Here is my initial list with thoughts:

* `add` - [done]
* `sub` - [done]
* `mul` - [in progress] difficult.
* `div` - once `mul` is working, shouldn't be too difficult.
* `sdiv` - skip for now? 
* `smod`- skip for now? 
* `mod` - skip for now? 
* `addmod` - skip for now? 
* `mulmod` - skip for now? 
* `exp` - skip for now? 
* `signextend` - skip for now? 
* `lt` - [kind of done], there is an implementation, but it can be improved.
* `gt` - similar to `lt`.
* `slt`- skip for now? 
* `sgt` - skip for now? 
* `eq` - [done]
* `iszero` - [done]
* `and` - [done]
* `or` - [done]
* `xor` - [done]
* `not`- easy, we should do it.
* `shl` - not sure how to do this yet, might require changes to the instruction set, but would be good to include it even now.
* `shr`- same as `shl`.
* `sar` - skip for now?

**Comment by grjte** [comment]
You’ve definitely spent more time considering this than I have, so I’ll need to look at it more to get a better feel for your list. What I should have said is that I would prefer to prioritize doing as many u256 as possible before doing u128.

**Comment by bobbinth** [comment]
For v0.1 release (which will accompany v0.2 release of the VM), we will include the following in the standard library:

* `math::u64`
* `crypto::hashes::blake3`
* `crypto::hashes::sha256`

I'm closing this issue and will open another one for v0.2 stdlib content.
