### ISSUE TITLE
Range checks for u32 operations

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#143]
As described in [u32 operations](https://hackmd.io/NC-yRmmtRQSvToTHb96e8Q) note, these operations need to rely on a set of helper registers. This is not yet implemented because the helper registers will actually be located in the decoder which is currently not implemented.

Some of the helper registers are needed to perform 16-bit range checks. And while we can't yet populate these registers with needed values, we can make lookups into the `RangeChecker` for for these value (this can be done via `RangeChecker::add_value()` method).

At the high level, there are two things we should do:
1. For u32 operations which require range checks, we should make sure we add the required values to the `RangeChecker`. It might make sense to have some helper functions to handle this rather than duplicating this lookup code in every operation handler.
2. Once the above is done, executing u32 operations would result in the `RangeChecker` trace being populated. We should integrate this trace into the overall execution trace similar to how we did this for co-processor execution traces.

**Comment by grjte** [comment]
Closed by #149 and #152 .
