### ISSUE TITLE
Use mdBook for documentation

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#147]
Currently, most of new documentation for Miden VM is kept in hackmd notes. We should probably transition to using [mdBook](https://rust-lang.github.io/mdBook/index.html) for Miden VM documentation. The good thing is that we can move most of the content with relatively little change as mdBook uses markdown file to build the final book (and it seems like we can use formulas in these files).

At the high level, the book will probably have the following sections.

* Introduction - high level description of the VM, its features etc.
* User documentation - this will also include description of Miden assembly.
* Design - this will include more in-depth description of the architecture and constraints.
* Background material - this could include some background material on STARKs, though we can probably add this later.

**Comment by itzmeanjan** [comment]
This is a good idea 👌

**Comment by bobbinth** [comment]
The new doc structure is deployed here: https://maticnetwork.github.io/miden

Now, we just need to migrate the content.
