### ISSUE TITLE
Integration tests for arithmetic field operations

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#165]
Tests for arithmetic field operations need to be added to the [integration tests](https://github.com/maticnetwork/miden/blob/next/miden/tests/integration/operations/field_ops.rs).

Tests should follow the existing pattern with the following tests for each of the arithmetic field operations that are missing tests:
- a test of simple success cases
- a test with applicable failure cases, if they exist (compilation and/or execution failure)
- a proptest of the expected success case

The [u32 arithmetic tests](https://github.com/maticnetwork/miden/blob/next/miden/tests/integration/operations/u32_ops/arithmetic_ops.rs) provide a fairly complete example.

Specs for the operations are in the [Miden Assembly note](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA).

The field operations which are missing tests are:

- [x] add
- [x] add.b
- [x] sub
- [x] sub.b
- [x] mul
- [x] mul.b
- [x] div
- [x] div.b
- [x] neg
- [x] inv

More information can also be seen in the [field_ops assembly parsers](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/field_ops.rs).

**Comment by bobbinth** [comment]
Closed by #170
