### ISSUE TITLE
Add overflowing shl and shr to u64 module in stdlib

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#168]
Currently, [u64 module](https://github.com/maticnetwork/miden/blob/next/stdlib/asm/math/u64.masm#L583) in stdlib implements only `unchecked` version of bitwise shift operations. It would be great to add the `overflowing` versions as well. Specifically:

* `overflowing_shl` would have the following stack transition: `[b, a_hi, a_lo, ...] -> [d_hi, d_lo, c_hi, c_lo, ...]`, where: 
  * `a_hi` and `a_lo` are the high and low 32-bit limbs of a 64-bit value `a`.
  * `b` specifies the number of bits to shift by. This value must be smaller than 64.
  * `c = a << b` where `c` is a 64-bit value represented by `c_hi` an `c_lo` 32-bit limbs.
  * `d` is a 64-bit value represented by `d_hi` and `d_lo` 32-bit limbs containing the bits "shifted out" of `a` as the result of the shift operation.
* `overflowing_shr` would have the following stack transition: `[b, a_hi, a_lo, ...] -> [d_hi, d_lo, c_hi, c_lo, ...]`, where: 
  * `a_hi` and `a_lo` are the high and low 32-bit limbs of a 64-bit value `a`.
  * `b` specifies the number of bits to shift by. This value must be smaller than 64.
  * `c = a >> b` where `c` is a 64-bit value represented by `c_hi` an `c_lo` 32-bit limbs.
  * `d` is a 64-bit value represented by `d_hi` and `d_lo` 32-bit limbs containing the bits "shifted out" of `a` as the result of the shift operation.

In mathematical terms `overflowing_shl` can be described as `a * 2^b -> (c, d)`. And `overflowing_shr` can be described as `a \\ 2^b -> c` and `a % 2^b -> d`.

Also to note, for these `overflowing` versions we do not need to very that the inputs are represented using valid 32-bit limbs. And we don't need to check if `b` is smaller than 64 as using `b` which is greater than 64 will cause `pow2` operation to fail.

**Comment by willyrgf** [comment]
I would like to work in this issue if no one is.

**Comment by bobbinth** [comment]
Awesome! Thank you. Go for it!

**Comment by willyrgf** [comment]
Do we have some kind of table which we can know how many cycle each instruction or group takes?

**Comment by bobbinth** [comment]
Yes, here it is: https://docs.google.com/spreadsheets/d/1vFNZipN43Tuv2kSQdLtAMhNn_xA2xCsek-fEjf0PlTk Most instructions are covered, though there are some towards the end which need to be filled in.

**Comment by willyrgf** [comment]
If I found any in this case I add them.
I'm trying to understand how many cycles my solution will take and try to improve it in some way.

**Comment by bobbinth** [comment]
Closed by #191
