### ISSUE TITLE
Project Contributions

### ISSUE THREAD

**Issue by robinsingh1** [maticnetwork/miden#17]
Hi there,

Is there a way to start contributing to Miden ?  Excited about the project would love to get involved in some capacity

Best,

**Comment by bobbinth** [comment]
Yep - in the next couple of weeks I'll write up quite a few more issues, which will hopefully be simple enough for people to get started. In the meantime, the best way forward is to explore some of the project internals (in the [next](https://github.com/maticnetwork/miden/tree/next) branch) and ask questions :)
