### ISSUE TITLE
Add min and max procedures to u64 stdlib module

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#172]
We should add basic `min` and `max` procedures to [u64 module](https://github.com/maticnetwork/miden/blob/next/stdlib/asm/math/u64.masm) in the standard library. Stack transitions for these procedures would look as follows:

* min: `[b, a, ...] -> [c, ...]` where `c = a` if `a < b` and otherwise `c = b`
* max: `[b, a, ...] -> [c, ...]` where `c = a` if `a > b` and otherwise `c = b`

These procedures will probably rely on less-then and/or greater-than comparison procedures from the same module as well as [conditional drop](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA#Conditional-manipulation) instructions.

**Comment by bobbinth** [comment]
@tohrnii - that would be awesome! Thank you. Feel free to submit a PR.

**Comment by tohrnii** [comment]
@bobbinth I've added a PR but not sure if the implementation is efficient. Please let me know if you think there's a better way. Thanks.

**Comment by bobbinth** [comment]
Closed by #181
