### ISSUE TITLE
Update the auxiliary table execution trace

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#178]
We need the following updates to the auxiliary table:

- [x] implement the execution trace for the [pow2 operation](https://hackmd.io/@grjte/H1oTEZQXc)
- [x] add the pow2 execution trace to the aux table by combining it with the bitwise execution trace
~- [ ] reorder the aux table co-processors to resolve the "last row problem" for memory processor transition constraints~

**Comment by grjte** [comment]
It turns out that swapping the order of memory and padding in the auxiliary table will be problematic once the pow2 trace is added, so here's a brief writeup of the auxiliary table design with a new proposed order:
https://hackmd.io/@grjte/ByKCo1Pr5

**Comment by grjte** [comment]
I think that a better approach to resolving the "last row problem" for the memory processor's transition constraints will be to use the "modified constraint format" discussed in the above note. This should make constraints easier to reason about and give more consistency across the other co-processors where this problem crops up. However, the details of the modified constraint format should be checked a bit more deeply so that:
- we have more surety that the changed format doesn't cause a problem with the constraints
- we have a sense of the tradeoff between the two sets of constraints in terms of number of constraints, degree of constraints, and number of multiplications.

I intend to write this up as part of #179.

**Comment by bobbinth** [comment]
Closed by #183
