### ISSUE TITLE
Mdbook links seem to be broken

### ISSUE THREAD

**Issue by tohrnii** [maticnetwork/miden#190]
A few links that are relative to README.md in the root directory seem to be broken on building mdbook. I suspect it has something to do with the difference in relative paths of these directories from docs and root. Tried building mdbook from both root and docs directories. Am I missing something? Not sure how to fix it.

**Comment by bobbinth** [comment]
Thank you for noticing! Not a big deal for now since we'll probably need to update main README quite substantially soon. But I'll keep this open until we do.

**Comment by bobbinth** [comment]
Fixed by #331
