### ISSUE TITLE
Optimize pow2 co-processor AIR constraints for output aggregation

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#199]
The pow2 co-processor currently uses 2 constraints for output aggregation, but we can do better.

The design of the pow2 processor and its current constraints are described [here](https://maticnetwork.github.io/miden/design/aux_table/pow2.html).
The implementation is [here](https://github.com/maticnetwork/miden/tree/next/air/src/aux_table/bitwise_pow2/pow2.rs).

It may be possible to reduce this to one constraint without changing the design of the table. If so, that would be optimal. Alternatively, @bobbinth provided this suggestion:

> I wonder if we could do better here. Right now, for every row we compute the sum twice, once for the current row and once for the next one. Since we are multiplying by small powers of two, this is not super expensive - but still, would be good to do it only once.
>
> For example, we could introduce an extra column which would be responsible for copying the value of z from the previous row. Assuming this doesn't increase the width of the auxiliary table beyond 18, this could be a much cheaper option.

Restrictions on the new constraint:
As mentioned in the docs in the pow2 processor file, the selector flags for this processor require degree 4. The maximum degree for constraints in Miden is 9, so any new constraint for output aggregation must be degree 5 or less without the flags.

**Comment by grjte** [comment]
As an additional note - the [bitwise co-processor ](https://maticnetwork.github.io/miden/design/aux_table/bitwise.html)also uses 2 constraints for output aggregation to handle the first row, then all the transition rows. The optimized construction that we come up with here can likely be reused there as well.

**Comment by 0xKanekiKen** [comment]
@grjte - Is it fine if I take this up?

**Comment by grjte** [comment]
@0xKanekiKen that would be great! Please let me know if you have any questions. We can chat directly if needed

**Comment by 0xKanekiKen** [comment]
@grjte: Thanks! We can chat on discord if it's fine with you.

**Comment by grjte** [comment]
Sure, that works!

**Comment by grjte** [comment]
Closed by #232
