### ISSUE TITLE
Platform Agnostic?

### ISSUE THREAD

**Issue by frisitano** [maticnetwork/miden#201]
Will miden be built in such a way that is platform agnostic / stateless?  This is to say that miden could be used on different platforms with different state storage via the implementation of an adaptor?  This is the approach that Move VM and SputnikVM have taken and it has been very effective in terms of adoption.

**Comment by bobbinth** [comment]
Miden VM is open-sourced under MIT license - so, anyone is free to use it. We will try to keep it as generic as possible, but might have to make some decisions which bias it toward Polygon Miden needs.

Regarding storage specifically - a lot is still TBD and we are planning to include storage mechanism by v0.3 release. There are some initial discussions related to this in #192

**Comment by frisitano** [comment]
perfect I'll give the discussion a read. Thanks!
