### ISSUE TITLE
Add program analysis to miden assembly playground

### ISSUE THREAD

**Issue by tohrnii** [maticnetwork/miden#204]
It would be nice to have total vm cycles count and other stats displayed alongside stack state in the wasm based miden assembly playground built by @timgestson [here](https://github.com/timgestson/miden-assembly-playground).

Needs issue #138 to be resolved which is being worked on in PR #198.

Suggested by @grjte [here](https://github.com/maticnetwork/miden/discussions/175#discussioncomment-2577818)

Please feel free to delete this issue if this is not the right place to track it.
Maybe we can fork timgestson's repo to maticnetwork org to work on it if possible to start building toward's @bobbinth's idea of something like evm.codes playground?

**Comment by tohrnii** [comment]
Demo with total vm cycles added: https://github.com/tohrnii/miden-assembly-playground

**Comment by grjte** [comment]
@tohrnii I love what you & @timgestson have done here and I think this is a great time to open this issue. 

Before we move forward I think we probably want to pause and consider how we want this tool to be so we can make some opinionated choices about stack, design, functionality, etc before we get too far along. That will help ensure that any work that's done on this is moving towards the implementation we'll want to release.

I'll give some more thought to it this week & we can revisit this when #138 is finished

**Comment by bobbinth** [comment]
Moved to https://github.com/0xPolygonMiden/examples/issues/29.
