### ISSUE TITLE
Update u32assert assembly instruction

### ISSUE THREAD

**Issue by 0xKanekiKen** [maticnetwork/miden#213]
`u32assert` instruction checks whether the top value of the stack is u32 or not. It is currently using 3 VM cycle using these three VM instructions: `U32SPLIT EQZ ASSERT`. We would like to update the assembly instruction with `PAD U32ASSERT2 DROP` as it gives a better error message as echoed by Bobbin in this [PR](https://github.com/maticnetwork/miden/pull/202). The test cases also needs to updated accordingly as some u32 operations might fail due to the assembly instruction udpate.

**Comment by DeimosTheMisthios** [comment]
I'd like to take a crack at this one, if still available?

**Comment by 0xKanekiKen** [comment]
Thanks, @DeimosTheMisthios! Please feel free to reach out to me if you have any queries.

**Comment by DeimosTheMisthios** [comment]
Thanks, let me know what you think of #215. I've added a comment that should perhaps be discussed: in cases where the result (and not the inputs) is >= 2^32, should the error by `FailedAssertion` or `NotU32Value` ?

https://github.com/maticnetwork/miden/blob/5e7680df5e842d2ea42c0696c0ba99a8421f31fe/miden/tests/integration/operations/u32_ops/arithmetic_ops.rs#L32-L51

**Comment by 0xKanekiKen** [comment]
Thanks @DeimosTheMisthios, for looking into it. We will have similar considerations with other operations. I think that we should leave these be for now as changing VM instruction logic will have an impact on downstream operations. However, I will defer to @bobbinth's opinion.

**Comment by bobbinth** [comment]
@DeimosTheMisthios thank you for tackling this and @0xKanekiKen thank you for handling the questions!

I agree that it would be good to update the error message, but I don't see a simple way of achieving this. So, for now, I think the best thing would be to create a separate issue for this so that we could come back to it later.

**Comment by bobbinth** [comment]
Closed by #215
