### ISSUE TITLE
Replace u32addc with u32add3 operation

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#220]
As discussed [here](https://github.com/maticnetwork/miden/issues/203#issuecomment-1127178122), we can generalize `U32ADDC` operation into `U32ADD3` operation. Stack transition for this operation would be very similar to `U32ADDC`:
```
[c, b, a, ... ] -> [e, d, ... ]
```
Where `d` and `e` would be the lower and the upper 32-bit limbs of `a + b + c`. The main difference between `U32ADDC` and `U32ADD3` is that in case of `U32ADD3` all 3 operands could be full 32-bit values, while in case of `U32ADDC`, the `a` operand must be a binary value (i.e., either 1 or 0).

Once the operation is updated, we should also update `u32addc` assembly instruction to `u32add3`.

**Comment by 0xKanekiKen** [comment]
I'll take care of it :)

**Comment by bobbinth** [comment]
Thank you! It is all yours :)

**Comment by bobbinth** [comment]
Closed by #221 .
