### ISSUE TITLE
Optimize range checker execution trace finalization / length check

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#229]
Currently, the 8-bit range check table is built twice when the execution trace is finalized.

1. It is built during the [call to `RangeChecker::trace_len`](https://github.com/maticnetwork/miden/blob/78f4b7d228aca6d0949ac37dc9854d6662a2ee8a/processor/src/trace.rs#L222) when the maximum length of the execution trace is being computed in `finalize_trace`.
2. It is built during the [`range.into_trace` call](https://github.com/maticnetwork/miden/blob/78f4b7d228aca6d0949ac37dc9854d6662a2ee8a/processor/src/trace.rs#L240) before the range checker's trace is combined into the final execution trace.

Ideally, it would be better to build this table just once. It is probably also worth checking the finalization of other processors to ensure there are no similar duplicated computations.

**Comment by 0xKanekiKen** [comment]
@grjte - I'd like to pick this up, if it's available?

**Comment by bobbinth** [comment]
Closed by #438
