### ISSUE TITLE
Compiling for no_std target

### ISSUE THREAD

**Issue by frisitano** [maticnetwork/miden#241]
Hi,

I was under the impression that `miden` was compatible with `no_std` targets however this does not appear to be the case in it's current form.  I think we need to add `#![cfg_attr(not(feature = "std"), no_std)]` to `lib.rs` in miden crates.  Where applicable we can add `use vm_core::utils::collections` which is a pub reference to `winter_utils::collections`.  We may also need to support macros (e.g. `vec!`) by making them available via `alloc`: 

```
#[cfg(not(feature = "std"))]
#[macro_use]
extern crate alloc;
```

Does this sound reasonable?

**Comment by bobbinth** [comment]
Hi - yes, this looks about right. And thank you for the PR! I'll review it in the next day or two.
