### ISSUE TITLE
Cleaner way to create ranges

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#245]
Currently, we have a utility function for creating `std::ops::Range` structs called [range()](https://github.com/maticnetwork/miden/blob/next/core/src/utils/mod.rs#L71). This function is convenient because it can be used to create `Range` structs using the start value and length of the range (rather than start and end values). However, the naming of the function is a bit unfortunate, and we actually import it as `create_range()` in various places.

A better approach might be to create an extension trait for the `Range` struct. Maybe something like `RangeExt`, and this trait would implement a `new()` function which would be similar to the current `range()` function. We can also add `len()` function to this trait which would return the length of the range (this might be convenient in the future).

Additionally, we could re-export `core::ops::Range` from the `core` crate. This way, when we want to work with ranges, we could just import `{Range, RangeExt}` from the core crate.

**Comment by 0xKanekiKen** [comment]
@bobbinth: I'd like to work on it.

**Comment by 0xKanekiKen** [comment]
@bobbinth: Understood, okay!

**Comment by frisitano** [comment]
I can pick this up @bobbinth

**Comment by bobbinth** [comment]
@frisitano - it is all yours! Thank you!

**Comment by frisitano** [comment]
Experiencing a slight challenge with the proposed solution.  The current `range()` function is a `const` (`pub const fn range(...)`).  However `const` functions cannot be defined within traits.  Therefore we are not able to implement a `const fn new(...)` function within the trait.  [Additionaly `len()` is already provided by the implementation of the `ExactSizeIterator` trait for `Range<usize>`](https://doc.rust-lang.org/core/ops/struct.Range.html#impl-ExactSizeIterator).

**Comment by bobbinth** [comment]
> However `const` functions cannot be defined within traits

Ah! I didn't realize this. It is possible to do const trait implementations (as in [here](https://github.com/rust-lang/rust/issues/67792)), but this is not yet stable.

I'll put this issue on hold for now. Thanks for looking into it!
