### ISSUE TITLE
Optimize bitwise co-processor AIR constraints for output aggregation

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#256]
The [bitwise co-processor ](https://maticnetwork.github.io/miden/design/aux_table/bitwise.html) uses 2 constraints for output aggregation. One constraint handles the first row, then the other handles all the transition rows, but this means that we compute the sum twice at every row. It can be optimized by adding a new column which tracks the previous output and then aggregating the sum once at each row instead of twice.

The same problem was already solved for the pow2 co-processor constraints (issue #199), so the same solution can be used here. These two bitwise constraints should be replaced with an optimized set of constraints analogous to the ones implemented in #232 (which resolved #199).

**Comment by DeimosTheMisthios** [comment]
Hello, can I pick this one up?

**Comment by grjte** [comment]
@DeimosTheMisthios sure, thanks! I've assigned it to you

**Comment by grjte** [comment]
Closed by #281
