### ISSUE TITLE
Move examples into .masm files?

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#288]
We have a few examples (not all of them working) to make it easier for people to play with the VM. Currently, the examples can be invoked via `miden examples` cli command. I am wondering if instead of having such a dedicated command we should move examples into `.masm` files which can be run using `miden run` command.

Such examples could go into `miden/examples` directory, and we could have a dedicated directory for each example containing the `.masm` and `.inputs` files.

Overall, I think it would be good to do this, but there are a couple of complications:
1. Some examples build the assembly code dynamically (e.g., the Fibonacci example) - I don't think we can support this with external `.masm` files.
2. In the current structure we also run the computation outside of the VM and then compare the results at the end. This allows us to use the examples for testing purposes. This structure would need to be updated somehow.

**Comment by tohrnii** [comment]
I am wondering if it's better to have examples in a more accessible form instead like having it as part of the planned miden assembly playground or in the form of tutorials + assembly playground and not have it as part of the main miden codebase?

**Comment by mariari** [comment]
It would be nice to have a good place to contribute examples. I have a few of my own that I've generated

[Fibonacci with the iteration amount from user input](https://github.com/anoma/zkp-compiler-shootout/blob/main/miden-assembler/miden/fib.masm)

[Sudoku verifier. Currently in the process of testing](https://github.com/anoma/zkp-compiler-shootout/blob/main/miden-assembler/miden/sudoku.masm)

[I also generate all these examples dynamically](https://github.com/anoma/zkp-compiler-shootout/blob/main/miden-assembler/src/programs.lisp#L12), however I think for the simple ones (dynamic fib) it is illustrative on their own, with more complex examples (the sudoku I've generated) being more fit for a blog post explaining the more specific Miden specific methodology when working with it.

**Comment by Dominik1999** [comment]
We have this Repo now for examples - https://github.com/0xPolygonMiden/examples. It is not filled yet, but I will migrate all examples over and make them work against the latest stable version. 

Not sure whether to keep the examples in Rust Files or create `.masm` and `.input` files. 

I love the idea if @tohrnii having a playground where we could showcase those examples.

**Comment by bobbinth** [comment]
I think to the extent possible, we should use `.masm` and `.input` files rather than code examples directly in Rust.

**Comment by Dominik1999** [comment]
ok, that makes it easier as well
