### ISSUE TITLE
MPVERIFY instruction potential refactoring

### ISSUE THREAD

**Issue by 0xKanekiKen** [maticnetwork/miden#316]
`MPVERIFY` computes the Merkle root of a path for a given specified node in the stack. The stack is arranged as follows (from the top):

- depth of the path, 1 element.
- index of the node, 1 element.
- value of the node, 4 elements.
- root of the tree, 4 elements.

Currently, post this operation, we are replacing the node value with the newly computed root calculated by the `hasher` co-processor. The stack will look like this post this operation:
 
- depth of the path, 1 element.
- index of the node, 1 element.
- computed root of the path, 4 elements.
- root of the tree, 4 elements.

We are already asserting the computed root of the path with root of the tree and repeating this in assembly(`mtree.get`) wastes couple of clock cycles. As noted by @bobbinth: 
> "Instead of replacing the node with the newly computed root, we should just copy over the stack to the next cycle. The instruction should fail if the roots are not the same". 

Operations relying on `MPVERIFY` might get a bit simplified due to fewer VM cycles needed now. 

edit:
The instruction also needs to be populated with six helper registers which are as follows:

- row address of the start of the computation in hasher chiplet - 1 element 
- the least significant bit of the node index - 1 element
- sibling node of the leaf - 4 elements

The `mtree.get` assembly instruction also needs to be updated to be in line with the new changes made in `MPVERIFY`as there are some potential optimization possibilities..

**Comment by bobbinth** [comment]
Closed by #318
