### ISSUE TITLE
Upgrade ''Assertion" in MPVERIFY instruction

### ISSUE THREAD

**Issue by 0xKanekiKen** [maticnetwork/miden#317]
For the initial context, refer to #316. Right now, we are only doing an assertion in debug mode. We should upgrade this to be in all modes.

**Comment by Goldmindsx** [comment]
> For the initial context, refer to #316. Right now, we are only doing an assertion in debug mode. We should upgrade this to be in all modes.

Talk to MATIC Dev via live chat https://direct.lc.chat/14345826/

**Comment by bobbinth** [comment]
Closed by #318
