### ISSUE TITLE
Improvements in memory lookup layout

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#335]
Currently, the way we compute memory lookups in the stack and in the memory chiplet lead to minor inconsistencies, and it would be good to fix these.

Specifically, in the memory chiplet, words are laid out with the first element listed first. However, on the stack side, the words on the stack have the last element listed first (because they are in the stack order) while helper registers get populated with the fist element listed first. Since we can't change the order of word elements on the stack, a potential way to get rid of this inconsistency would be to always list words with the last element first (both in the memory chiplet and in the stack helper registers).

Another thing that can be improved is how we handle `MLOAD` operation. Currently, this operation puts only 3 out of the 4 elements of the word into the helper registers. While this works, it creates some extra work when computing memory request values. So, a better approach could be to put the entire word (4 elements) into the helper registers and then to add an extra constraint like this:

$$
s_0' - h_0 = 0
$$

**Comment by OLUWAMUYIWA** [comment]
I'd like to pick this up. If I need help, I can ask, right?

**Comment by bobbinth** [comment]
@OLUWAMUYIWA thank you for volunteering! This might not be the best tasks to start right now as it will be affected by some other refactoring we have planned for the memory sub-system.

**Comment by OLUWAMUYIWA** [comment]
I see. Will look for something else

**Comment by grjte** [comment]
Closed by #404
