### ISSUE TITLE
Add assembly instruction cycle costs to the user documentation

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#351]
It's a fairly natural expectation for people writing assembly code that operations will have the same costs and be one cycle each, but this is not the case for Miden assembly, since it's actually a lift from our VM instruction set, designed to make it more usable.

As a result, people may tend write Miden Assembly code that is significantly more expensive than necessary or than they realize, since the costs are a bit opaque right now.

Therefore, it will improve usability if we add cycle costs for each operation alongside its description in the [user documentation](https://maticnetwork.github.io/miden/user_docs/assembly/main.html), and it would be nice to do this before the v0.2 release.

We should address this in 2 parts:

- [x] update the existing cycle costs [spreadsheet](https://docs.google.com/spreadsheets/d/1vFNZipN43Tuv2kSQdLtAMhNn_xA2xCsek-fEjf0PlTk/edit?usp=sharing), which is incomplete and outdated (e.g. some ops are missing costs;  ops like` u32add3` are missing; function names haven't been updated to match the recent renaming to `u32checked_`/`u32unchecked_`/`u32wrapping_`/`u32overflowing_`). cycle cost information is mostly listed in the inline documentation next to each parser operation in the code base. For example, the cycle cost for `rphash` is listed above the `parse_rphash` function [here](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/crypto_ops.rs). However, in some cases it may need to be calculated.
- [x] update the documentation with the costs from the spreadsheet. We'll need to think about how best to do this so that we maintain the readability & formatting of the formulas and information in the "notes" on each instruction.

**Comment by grjte** [comment]
Note: in the longer run, it would be nice to have this get automatically calculated and updated, but this is probably a little ways off, so filling it in manually for now should improve the experience of anyone working in Miden Assembly, even if it does end up getting a bit out of sync

**Comment by itzmeanjan** [comment]
This is really a good idea 👍

**Comment by tohrnii** [comment]
I've created a gist of the spreadsheet with updated cycle costs: https://gist.github.com/tohrnii/21a78247e2df8a9938686cd98122201b
Also, maybe we should have a spreadsheet with cycle costs for stdlib procedures sometime in the future too.

**Comment by grjte** [comment]
Thanks @tohrnii! I think having the stdlib costs somewhere makes sense as well.

**Comment by bobbinth** [comment]
@tohrnii - looks great! Looks like we have an issue `push.local.i` and `pop.local.i`. Unlike `push.mem` and `pop.mem`, it seems like they haven't been updated to use `MLOAD` and `MSTORE` operations.

**Comment by bobbinth** [comment]
Closed by #359
