### ISSUE TITLE
New assembly instruction

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#357]
While going through the u64 module in stdlib, I noticed that some patterns of instructions are used frequently, and I'm wondering if it is worth implementing assembly instructions for them.

One such sequence is: `eq.0 assert` which asserts that the top of the stack is zero. An assembly instruction to do this could be called `assertz`.

Another such sequence is `u32overflowing_madd drop` which is just a wrapping version of this operation. An assembly instruction for this would be `u32wrapping_madd`. And for consistency, we should probably add `u32wrapping_add3` as well.

**Comment by OLUWAMUYIWA** [comment]
Would love to work on this

**Comment by bobbinth** [comment]
@OLUWAMUYIWA - thank you for volunteering! It is all yours.

**Comment by OLUWAMUYIWA** [comment]
Sure. On it. Thanks

**Comment by bobbinth** [comment]
Closed by #387
