### ISSUE TITLE
Fix unescaped character failures during assembly module build process

### ISSUE THREAD

**Issue by maxgillett** [maticnetwork/miden#399]
When generating combined assembly module file `asm.rs`, a backlash within commented code in a `.masm` file produces an unknown character escape error and causes the build process to fail. This has been addressed by switching to a raw string literal in the pending commit https://github.com/maticnetwork/miden/pull/373/commits/59b20b5688d33426a0d7ee32f01e2afdd06ee0de, but we should ensure that this change does not have any unintended consequences.

**Comment by bobbinth** [comment]
Closed by #458.
