### ISSUE TITLE
Advice Providers from the standalone binary

### ISSUE THREAD

**Issue by mariari** [maticnetwork/miden#407]
I'm trying to test some miden code I've generated from the standalone binary, but it seems like there is no way to feed the binary with a starting advice provider

```rust
// src/cli/data.rs
    // TODO add handling of advice provider inputs
    pub fn get_program_inputs(&self) -> ProgramInputs {
        ProgramInputs::from_stack_inputs(&self.stack_init()).unwrap()
    }
```

Is there any way to accomplish this currently?

**Comment by bobbinth** [comment]
With #408 it is now possible to provide values for populating the advice tape, but as I mentioned above, a more comprehensive support will be added after #406 is done.

**Comment by mariari** [comment]
Thank you for the quick change in #408, it seems I'm still getting `Executing program... Failed to generate exection trace = EmptyAdviceTape(1)` however
