### ISSUE TITLE
Memory layout of procedure locals

### ISSUE THREAD

**Issue by Al-Kindi-0** [maticnetwork/miden#417]
The current issue is related to procedure locals. The following example illustrates the issue:

```       

        proc.outer.2
            locaddr.0
            add.1
            locaddr.1
            assert_eq


        end
        begin
            exec.outer
        end
```
Intuitively, the following code should work but it raises an error because of the assertion. After discussing it with @bobbinth, it seems that the memory layout is not in increasing order but is decreasing. This means that the above code should work when substituting `add.1` with `sub.1` and that is in fact the case.
I think, and @bobbinth too, that it is better to have the layout in an increasing order, unless there are any strong arguments for the current design. The required changes should be pretty much straightforward but it would be great to hear from everybody, and especially @itzmeanjan , if this might create any issues with some of our current implementations.

**Comment by bobbinth** [comment]
Closed by #421
