### ISSUE TITLE
Create Miden REPL

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#423]
We'd like to create a REPL in the processor crate that works like the [one](https://github.com/ControlCplusControlV/Scribe/pull/13) in the [Scribe project](https://github.com/ControlCplusControlV/Scribe), but with the following changes:

* Print out instructions message on startup
* Use a prefix for REPL commands to avoid future potential collisions with assembly instructions (e.g., maybe something like !stack or :stack instead of just stack).
* Add memory (or just mem) command to print out state of memory with support for indexing. For example, mem prints out the whole state of memory, but mem[1] prints out memory at address 1.
* When printing out stack state, include data from the overflow table (maybe separated by | from the top 16 values).
* When an instruction is entered, maybe print out stack state immediately. Or maybe have an option for two different modes.

**Comment by bobbinth** [comment]
Closed by #440.
