### ISSUE TITLE
Consider using `release` for CI tests

### ISSUE THREAD

**Issue by vlopes11** [maticnetwork/miden#433]
Currently the CI check is taking several minutes.

We can sacrifice build time to improve the test execution by adding the argument `--release` to the CI tests

https://github.com/maticnetwork/miden/blob/30afebad83fae8651f25d65e739c907b94d678d9/.github/workflows/ci.yml#L28

**Comment by 0xKanekiKen** [comment]
We have a few `debug_assert` statements in the VM which doesn't run in release mode. We used to build tests in release mode earlier to make it faster, but then in some cases, these `debug_assert` statements were failing locally but passing on GitHub. Thus we decided to revert to building tests in debug mode.

**Comment by grjte** [comment]
Yep, thanks @0xKanekiKen. We're definitely open to other ideas for speeding up test execution though. One thing we've discussed - there are quite a few full "prove and verify" air tests now in the integration tests in the Miden crate, and these are slow. Condensing them into just a couple full tests (and ensuring sufficient unit tests instead) would help reduce the time

**Comment by vlopes11** [comment]
Sounds good, its clear!

We have one alternative that is to enable debug assertions for the release mode.

Assuming we have an example like this:

```rust
#[test]
fn it_works() {
    debug_assert!(false);
}
```

If we `$ cargo test`, it will naturally fail, and will pass if we `$ cargo test --release`

However, if we enable the assertion, it will fail (as we want to) for both of the following cases

`$ RUSTFLAGS="-C opt-level=3 -C debug-assertions" cargo test`
`$ RUSTFLAGS="-C debug-assertions" cargo test --release`

We naturally want to be careful with this topic and certainly go to the safer path if we have doubts, but I think this would work without major issues.

**Comment by grjte** [comment]
Great! Thanks for the suggestion

**Comment by bobbinth** [comment]
Closed by #435
