### ISSUE TITLE
Optimize bytes serializer for Assembly

### ISSUE THREAD

**Issue by vlopes11** [maticnetwork/miden#462]
Currently, the bytes serializer users internally an allocated `Vec<u8>`

This allocation is not necessary and it could work with a slice of bytes in order to optimize its runtime overhead

https://github.com/maticnetwork/miden/blob/4553652a2a91e269d085415ebbe1cc3e49b715ba/assembly/src/parsers/ast/mod.rs#L59

_Originally posted by @bobbinth in https://github.com/maticnetwork/miden/pull/461#discussion_r1012527541_

**Comment by amankrx** [comment]
Hey, Can I work on this issue?

**Comment by vlopes11** [comment]
> Hey, Can I work on this issue?

from my side, most definitely welcome! just double check with @bobbinth and @grjte

**Comment by bobbinth** [comment]
@amankrx - that would be awesome! I've assigned it to you. Thank you!

**Comment by bobbinth** [comment]
Closed by #472. Thank you @amankrx again for fixing this!

**Comment by amankrx** [comment]
Thanks for assigning me this issue. Will learn a bit more about this, and contribute again soon.
