### ISSUE TITLE
Pick a digest for procedure ID computation

### ISSUE THREAD

**Issue by vlopes11** [maticnetwork/miden#463]
The procedure ID must be a deterministic computation that consumes as argument the label of the procedure.

Most likely it should be a broadly used efficient hash such as blake3 or sha256, truncated to the size of the procedure id

_Originally posted by @vlopes11 in https://github.com/maticnetwork/miden/pull/461#discussion_r1012762841_

**Comment by bobbinth** [comment]
We already use `BLAKE3` for this (e.g., [here](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/ast/context.rs#L314). We should just propagate this struct to all applicable places (e.g., to [here](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/ast/nodes.rs#L240)).

In the future, once [this](https://github.com/0xPolygonMiden/crypto/issues/6) is implemented, we'll switch the digest to 20 bytes.

**Comment by bobbinth** [comment]
Closed by #468
