### ISSUE TITLE
Reduce stdlib module provider to a single mapping

### ISSUE THREAD

**Issue by vlopes11** [maticnetwork/miden#465]
Currently, to support legacy implementation, we provide multiple mappings in stdlib so it will have a minimal impact downstream.

However, it is desirable to have these as a single id |-> ast mapping

_Originally posted by @vlopes11 in https://github.com/maticnetwork/miden/pull/461#discussion_r1012764915_

**Comment by bobbinth** [comment]
Closed by #531 and others.
