### ISSUE TITLE
'main transition constraint 1 did not evaluate to ZERO at step 103' 

### ISSUE THREAD

**Issue by Dominik1999** [maticnetwork/miden#466]
I encounter weird behaviour with either Miden or my code. 

When I try to prove my example Assembler Code importing Miden, I get 
```
thread 'main' panicked at 'main transition constraint 1 did not evaluate to ZERO at step 103', /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.1/src/trace/mod.rs:195:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: winter_prover::trace::Trace::validate
             at /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.1/src/trace/mod.rs:195:17
   3: winter_prover::Prover::generate_proof
             at /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.1/src/lib.rs:294:9
   4: winter_prover::Prover::prove
             at /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.1/src/lib.rs:175:49
   5: miden_prover::prove
             at /Users/ich/.cargo/git/checkouts/miden-4241ff496f7b0a1f/4553652/prover/src/lib.rs:64:17
   6: minimal_example::main
             at ./src/main.rs:103:28
   7: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here is a min example of a program. It is related to the `if.true` procedure, see @0xKanekiKen 's comment below.

```
begin
    push.1
    if.true
        dup
    else
        dup
    end
end
```
I created an example repo to reproduce because it might also be wrong imports, see here https://github.com/Dominik1999/minimal_example

However, when I run the same Assembly `program` and `inputs` in the CLI against the current `next` branch, there is no error, and the execution is proven. 

So somehow, the Miden Assembler that I import in the example above fails interpreting a `1` as `true`.

**Comment by Dominik1999** [comment]
the `stack_init` get's correctly deserialized as `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0]`

**Comment by 0xKanekiKen** [comment]
The issue seems to be in the overflow stack air constraint, particularly the constraint that enforces the `stack depth`.

After a glance, I see the following on the step where we are facing this issue:
`operation flag`: `split` opcode is the only non-zero, but it's not a one either - `4294967295` is the flag value I'm seeing.
opcode value in current frame: `[4294967295, 0, 4294967295, 4294967295, 4294967295, 0, 0]`. For `split`, it should be `1011100`
stack values: `[0, 4294967295, 4294967295, 4294967295, 0, 0 ...]`

We must investigate why we have non-binary values in individual bits of the opcodes.

**Comment by Dominik1999** [comment]
Got it. One day you need to show me how you debug this. Looks super interesting. One question though, in Miden Assembly 
`[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0]` is treated as bool, right? So I do not need to write `[false, true, ...]`?

**Comment by Dominik1999** [comment]
Also, all my examples here fail if there is a `if.true` procedure ...

https://github.com/0xPolygonMiden/examples/pull/3/files

**Comment by Dominik1999** [comment]
ok, so as a min example, even this fails:
```
begin
    push.1
    if.true
        dup
    else
        dup
    end
end
```

with 

```
thread 'main' panicked at 'main transition constraint 1 did not evaluate to ZERO at step 5', /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.1/src/trace/mod.rs:195:17
```

**Comment by bobbinth** [comment]
@Dominik1999 - this should be fixed by #479. Could you verify and if all looks good close this issue?

**Comment by Dominik1999** [comment]
@0xKanekiKen @bobbinth thanks a lot. 

It might be me, but when I run my min. example or Game of Life using 

```
miden = { git = "https://github.com/maticnetwork/miden", branch = "next", package = "miden", default-features = false}
```

and building it new. The same error message appears:

```
thread 'main' panicked at 'main transition constraint 1 did not evaluate to ZERO at step 5', /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.1/src/trace/mod.rs:195:17
```

**Comment by 0xKanekiKen** [comment]
@Dominik1999: Can you try running the example by deleting the cargo.lock file? I think it's not using the up to date `next` branch of Miden.

**Comment by Dominik1999** [comment]
Works now like a charm when I use this import:

```
miden = { git = "https://github.com/maticnetwork/miden", rev = "e203f6657cd15d6de45a32d829fd2d850935432d", default-features = false}
```

This should be better with the new release. Then I can simply import the package, right?
