### ISSUE TITLE
Update user docs for v0.3 release

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#484]
We introduced quite a few new things for v0.4 release. Some of them have already been described in the docs, but many haven't. We should update the docs to explain how to use these features. The things that still need to be documented are (though, maybe I'm missing something):

* Memory contexts and layouts.
* Semantics of a a CALL instruction.
* Kernels and semantics of a SYSCALL instruction.

This would also include updating program structure docs (i.e., MAST description).

**Comment by grjte** [comment]
The advice map doesn't seem to be in the user docs. Should this be added too?

**Comment by bobbinth** [comment]
Closed by #542
