### ISSUE TITLE
Change `mem_store` to drop the stored value from the stack

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#500]
`mem_load` pushes a single element onto the stack, whereas `mem_store` saves an element in memory and leaves it at the top of the stack. In practice, `mem_store` seems to almost always be used in conjunction with `drop` (e.g. `mem_store.1 drop`).

It seems to make sense to change `mem_store` so that it mirrors the `mem_load` functionality by popping the element off the stack and then storing it.

The new `mem_store` would look like this:
stack: `[a, v, ...]` -> `[ ... ]`
`v` -> `mem[a][0]`

@itzmeanjan @bobbinth @calummoore please let me know if you disagree with this proposed change.

**Comment by bobbinth** [comment]
I agree with this change. I checked `stdlib` files and we always have `mem_store drop` sequence.

One note: if we are making this change, we should also do the same thing with `loc_store` instruction (it is also always followed by `drop` in `stdlib` files).

Let's add this to v0.3 (but we should implement this in the new assembler structure).

**Comment by bergkvist** [comment]
Is there a reason `loc_storew` doesn't call `dropw`, when `loc_store` calls `drop`?

**Comment by bobbinth** [comment]
This is mostly for efficiency reasons: dropping 4 elements takes 4 VM cycles and frequently when the save some value to memory, we need to load another value right after it. So, we can do something like `loc_storew.x loc_loadw.y` and this avoids extra 8 cycles which would have been used to first drop 4 elements from the stack and then push 4 new elements onto the stack.
