### ISSUE TITLE
`adv_loadw` and stdlib

### ISSUE THREAD

**Issue by Al-Kindi-0** [maticnetwork/miden#506]
After rebasing from the latest `next`, including the instruction `adv_loadw` gives the following error:

```
  process didn't exit successfully: `/home/miden/target/debug/build/miden-stdlib-024dc314a8bdb603/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=asm

  --- stderr
  Error: Custom { kind: Other, error: "malformed instruction 'adv_loadw': missing required parameter" }
```

A minimal failing example can be the following procedure anywhere in `stdlib`:
```
proc.failing_procedure
    adv_loadw
end

```

The PR solving this issue should include a failure test in the spirit of the above.

**Comment by grjte** [comment]
Since the error is a parsing failure, I think the test for this should just be a unit test in the assembly crate of the `adv_loadw` parser

**Comment by tohrnii** [comment]
I think PR #513 by @vlopes11 has a fix for the issue. I was going to submit PR with a similar fix. Maybe we can close this issue after that PR is merged?

**Comment by vlopes11** [comment]
@tohrnii yes, it will indeed fix that problem. we expect to merge 513 soon, but it might be worthy to create an isolated PR to fix that specific issue if we need this fix to land ASAP

**Comment by Al-Kindi-0** [comment]
Trying to sidestep the problem by substituting `adv_loadw` with their `adv_push` equivalent, I found this new but I believe related error:
```
Caused by:
  process didn't exit successfully: `/home/miden/target/debug/build/miden-stdlib-024dc314a8bdb603/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=asm

  --- stderr
  Error: Custom { kind: Other, error: "unexpected token: expected 'adv.u64div' but was 'adv.keyval'" }
warning: build failed, waiting for other jobs to finish...
```

**Comment by tohrnii** [comment]
@Al-Kindi-0 There is an open issue #493 for that.

**Comment by Al-Kindi-0** [comment]
> @Al-Kindi-0 There is an open issue #493 for that. I'll submit a PR for that as well.

Thanks @tohrnii

**Comment by tohrnii** [comment]
Closed by #517.

**Comment by bobbinth** [comment]
@tohrnii @Al-Kindi-0 - could we double check if this works against the latest `next` branch?

**Comment by Al-Kindi-0** [comment]
I can confirm that this solved the issues above for me.
