### ISSUE TITLE
Can't import libraries in Assembly - assembly error at 0: module source not found: std::crypto::hashes::blake3

### ISSUE THREAD

**Issue by Dominik1999** [maticnetwork/miden#510]
I want to import miden and its modules into a small program. So I also import every module via the miden crate.

When I try to compile a simple program that imports a library, I get the following: 

```
Could not compile source: assembly error at 0: module source not found: std::crypto::hashes::blake3
```

This is the program:

```
use miden::{Assembler, Program}

fn main() {

    // Miden Assembly blake3
    let source_blake3 = String::from("  
    use.std::crypto::hashes::blake3

    begin
        exec.blake3::hash
    end");

    let assembler = Assembler::new();
    let program: Program = assembler.compile(source_blake3.as_str()).expect("Could not compile source");
}
```
If I don't import the library and write a super simple Assembly program - `begin push.1 end` it works.

I import Miden in my `Cargo.toml` like:

```
[package]
name = "zkp-benchmarking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
miden = { git = "https://github.com/maticnetwork/miden", branch = "next", default-features = false }
```

___

To me, there are two different questions:

- To me, it is unclear how users should use/import the Miden VM into their code. Maybe we need a section in the docs to explain it?
- How can I debug?

**Comment by grjte** [comment]
Hi @Dominik1999 thanks for bringing this up. Part of the confusion is that things have changed in the new release and the docs are lagging a bit, so we do indeed need to update. I think it would also be great to add an example that uses the standard library in our examples repo.

The main issue here is that you're not providing the library to the `Assembler`, so it doesn't know about it. You can see some examples for what to do by looking at the [CLI implementation](https://github.com/maticnetwork/miden/blob/268742dda05d5383e61fe0c533db00dbf8b19c27/miden/src/cli/data.rs#L182).

Essentially, your program should work if you make the following changes:

## Add the standard library to your `Cargo.toml` file

```
[dependencies]
miden = { git = "https://github.com/maticnetwork/miden", branch = "next", default-features = false }
miden-stdlib = { git = "https://github.com/maticnetwork/miden", branch = "next", package="miden-stdlib", default-features = false }
```

## Provide the standard library to your `Assembler`

```
use miden::{Assembler, Program};
use miden_stdlib::StdLibrary;

fn main() {
    // Miden Assembly blake3
    let source_blake3 = String::from(
        "  
    use.std::crypto::hashes::blake3

    begin
        exec.blake3::hash
    end",
    );

    let assembler = Assembler::new().with_module_provider(StdLibrary::default());
    let program: Program = assembler
        .compile(source_blake3.as_str())
        .expect("Could not compile source");
}
```

**Comment by Dominik1999** [comment]
Thanks grjte!

Now the Assembler finds the module and compiles. 

But proving the program results in 

```
thread 'main' panicked at 'main transition constraint 77 did not evaluate to ZERO at step 210', /Users/ich/.cargo/registry/src/github.com-1ecc6299db9ec823/winter-prover-0.4.2/src/trace/mod.rs:195:17
```

Maybe I should wait for the new release?

**Comment by 0xKanekiKen** [comment]
@Dominik1999 With #543, the issue should be gone. Can you rerun the blake3 example and confirm if the problem persists?

**Comment by bobbinth** [comment]
@0xKanekiKen - yes, this seems to be working now.
