### ISSUE TITLE
Recursive ZKP?

### ISSUE THREAD

**Issue by matthiasgoergens** [maticnetwork/miden#511]
Are there any plans to introduce recursive proofs?  Ie proofs that include validation of other proofs?

Ideally, perhaps via a new instruction in MASM?

**Comment by Al-Kindi-0** [comment]
Hey @matthiasgoergens ! Thank you for reaching out and sorry for the late answer.
Yes, we are planning to add support for recursive proof verification. A first step is in the following tracking issue #564 and the other (sub-)issues referring to it.
Please feel free to add any comments, ideas or even contributions.

**Comment by matthiasgoergens** [comment]
Thanks.  I'll close this issue in favour of the one you mentioned.
