### ISSUE TITLE
Review interior mutability of assembler

### ISSUE THREAD

**Issue by vlopes11** [maticnetwork/miden#540]
The assembler uses an internal cache to store the compiled procedures so these can be reused in further call/exec instructions without the need to recompile.

It is desirable persist the state of this cache through different compilations so procedures that are often used in different programs won't need to be recompiled.

Currently, that cache is part of the assembler state. It is so to avoid creating unnecessary complexity for the user that ideally should just invoke an immutable assembler - maybe even a static one - and perform the compilation, without having to worry about state management.

To achieve that simplicity, a cast from immutable to mutable was used. This can cause some problems to sync in Rust because the compiler will make assumptions since the function takes the assembler as immutable - when in fact the state is mutated. To mitigate this problem, a `Pin<Box<_>>` was introduced for the type. It will prevent the compiler from moving the reference around, and will force synchronizations to be performed sequentially.

This however might be the source of undefined behavior, so we need to make an in-depth analysis on how the compiler is managing the synchronization of this instance - also keeping in mind an eventual future requirement of thread-safety. Another point to check is the compilation for different architectures, including no-std WASM. If any critical problem with this approach is found, we might have to go for some alternatives.

#### AssemblerCache

Having a structure that will be passed as argument to the compile function and it will store the compiled procedures. It is the safest option, but we transfer the responsibility of management of this cache to the user, and make the API less ergonomic since we require more types for it to work.

#### Mutex/RwLock

We can store the procedure cache behind a mutex/rwlock. This is a safe and performant option, and will have the advantage of allowing the same cache to exist for multi-threaded compilation. However, this will require the use of a 3rd party library for no-std compilation since Rust lang provides RwLock/Mutex only for std.

#### Static space

We can store the procedure cache in the static space of the program and unsafely update it at the end of every compilation. This is more flexible than the mutex/rwlock alternative, but less robust since we bring to ourselves the responsibility to implement a reliable syncrhonization strategy. We might also have trouble to eventually clear this cache so it will grow indefinitely - possibly until the exhaustion of the host.

https://github.com/maticnetwork/miden/blob/7812976b00d504f67b45fbeda8adc3f8fedd1ca5/assembly/src/assembler/mod.rs#L178-L182

**Comment by bobbinth** [comment]
Closed by #561
