### ISSUE TITLE
Refactor the immediate value for checked u32 instructions

### ISSUE THREAD

**Issue by vlopes11** [maticnetwork/miden#541]
`u32mul` requires two valid `u32` in the stack for it to work properly.

At parse/compilation level, we shouldn't allow invalid immediate values to generate a program. Even if these might fail at runtime, we should be able to provide a consistent feedback to the user, provided a wrong (not necessarily malicious) input.

In this code, an attempt to rotate with an immediate value of `0` will cause an invalid immediate value outside `u32` boundaries. `1 << 32 - imm |-> 1 << 32 - 0 |-> 1 << 32`

One alternative is to forbid rotate with `0` as immediate. However, this might not be intuitive for the users, so it might be best to produce a noop in such cases. If we opt for the latter, then we will need to refactor the u32 ops implementation to reproduce the same behavior with the other bitwise operations.

https://github.com/maticnetwork/miden/blob/61cac203ff6584c05849c818d166586da75c1da3/assembly/src/assembler/instruction/u32_ops.rs#L303-L306

**Comment by bobbinth** [comment]
Closed by #572.
