### ISSUE TITLE
Module provider and library trait refactoring

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#552]
Currently, we have two traits for specifying interfaces for 3rd-party modules: `ModuleProvider` and `Library`. These look like so:
```Rust
pub trait ModuleProvider {
    fn get_module(&self, id: &ProcedureId) -> Option<NamedModuleAst<'_>>;
}

pub trait Library {
    type Module;

    fn root_ns(&self) -> &str;
    fn version(&self) -> &str;
    fn get_module(&self, module_path: &str) -> Result<&Self::Module, LibraryError>;
}
```

`Library` is actually kind of a useless trait as it currently isn't really used for anything. `ModuleProvider` is provided to the `Assembler` via the `with_module_provider()` method which looks like so:
```Rust
pub fn with_module_provider<P>(mut self, provider: P) -> Self
where
    P: ModuleProvider + 'static
```

I think this structure is somewhat confusing and can be improved.

First, we could make `Library` the primary way for people to define 3-rd party libraries. The functionality we need form a library is to return all modules contained in the library. The new `Library` trait could look as follows:
```Rust
pub trait Library {
    type Module;

    fn root_ns(&self) -> &str;
    fn version(&self) -> &str;
    fn modules(&self) -> ModuleIterator;
}
```
Where `ModuleIterator` could be some iterator which iterates over all modules in the library and returns tuples `(module_path, module_ast)`.

Next, we could convert `ModuleProvider` into a struct as I don't think we'll need it to be a trait. This struct could look similar to this:
```Rust
#[derive(Default)]
pub struct ModuleProvider {
    modules: Vec<(String, ModuleAst)>,
    proc_to_module: BTreeMap<ProcedureId, usize>,
}

impl ModuleProvider {
    pub fn add_library(&mut self, library: &dyn Library) -> Self {
        ...
    }
}
```

Inside the `add_library()` method, we'd iterate over all modules in the library, process them, and populate the internal data structures of the `ModuleProvider`.

Next, we'd change the `with_module_provider()` method of the `Assembler` into `with_libraries()` which would look something like this:
```
pub fn with_libraries(mut self, libraries: &[&dyn Library]) -> Self
```
Inside this method, we'd call `ModuleProvider::add_library()` for all libraries in the provided list.

In our context, we'd need to implement the new `Library` trait for the `StandardLibrary` class (which should be trivial). And we could also provide another implementation of `Library` - e.g., something like `FsLibrary` which would allow instantiating libraries from serialized library files described in #469.

**Comment by vlopes11** [comment]
Closed by #579
