### ISSUE TITLE
Management of local variables in memory

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#73]
As described in the assembly [specs](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA), Miden VM has word-addressable read-write memory. There are a few `load` and `store` instructions which are responsible for moving data between the memory and the stack. These instructions take memory address from the top of the stack.

From code organization standpoint, Miden assembly supports *procedures* and (will support) *functions*. The difference between the two is as follows:
* Procedures are in-lined into the program MAST at compilation time. Thus, semantically, procedures don't differ from the surrounding code. This, for example, means that they can access the same memory as surrounding context.
* Functions will be used to represent "untrusted" procedures (one use cases for these is cross-contract calls). A called function won't have access to the caller's memory and vice versa (this also implies that all parameters are passed by value between functions via the stack, but that's a separate topic).

In the context of managing local variables, we have the following situations to consider:
* Local variables for simple procedures (simple here means that all local variables can live on the stack).
* Local variable for complex procedures.
* Local variables for functions.

Handling local variables for simple procedures is straight forward - all variables live on the stack and the procedure doesn't need to allocate memory for storing locals. Similarly, handling local variables for functions is straight forward: each function gets its own memory and can place variables w/e it sees fit.

However, for complex procedures which can't fit all locals onto the stack, it is not immediately clear where they should store locals in memory to make sure one procedure doesn't overwrite locals of another procedure. There are several approaches to handle this.

### Option 1
We can do something similar to what the EVM does: have a convention for putting the "free memory pointer" (`fmp`) somewhere in memory (in our case, probably at address 0x0) and then use this free memory pointer to indicate where a procedure could put its locals.

This is the simplest approach in terms of implementation (we don't need to change anything at the VM level), but it would introduce quite a bit of runtime overhead. Basically, each time we need to read or write a local variable to memory, we'd need to read and possibly overwrite `fmp` value. Thus, in the worst case, each access to a local variable may require 2 - 3 memory accesses and a bunch of instructions in-between. Overall, I'd expect moving local variables between stack and memory to take up dozens of VM cycles with this approach.

### Option 2
We can still store `fmp` at address 0x0, but we would modify the semantics of load and store operations to implicitly read from this address, add the value at the top of the stack to the `fmp` and that would be the memory address for the operation. Basically, the memory address would be computed as: `mem[0] + stack[0]`, but this would be done implicitly.

This would reduce the number of cycles we'd have to expand, but we would still need to read write `fmp` from memory which would add rows to the memory trace.

### Option 3
We can have a dedicated register for `fmp` and would modify the semantics of load and store instructions to compute addresses as `fmp + stack[0]` (basically, top of the stack provides an offset relative to `fmp`). The value of `fmp` would be set to `0` at the start of the program.

The advantage of this approach is that we drastically cut down on the number of cycles consumed by load and store operations, and each load/store still translates to a single memory operation. The downsides are twofold:
1. We need to allocate extra register for `fmp` which would only be used for the purposes of load/store operations. I don't think this is a big deal.
2. We need to have a way to set and (possibly) get the value in `fmp` for this we would need to have 1 or 2 dedicated instructions.

The reason I said *possibly* for getting the value of `fmp` is because we might be able to get away with just setting the value using relative offsets. For example, if a procedure needed to allocate 3 words of memory for its locals it could do something like this:

```
push.3 setfmp
```

This would be equivalent to `fmp` ← `fmp + 3`. And then the procedure could store its locals at addresses `fmp`, `fmp - 1`, and `fmp - 2`.

Once the procedure is done, it could reset the value in `fmp` as follows:

```
push.3 neg setfmp
```

This would be equivalent to `fmp` ← `fmp - 3`. We could also change the format of `push` instruction to accept negative values to make this a bit more ergonomic.

Simple procedures which don't need to store locals in memory won't need to touch values in `fmp` at all.

One major drawback of options 2 and 3 is that managing absolute memory pointers becomes very tricky (and maybe even impossible). So, probably more thinking is needed here.

**Comment by bobbinth** [comment]
### Option 4

We keep `fmp` as a separate register as in option 3, but we don't modify the semantics of load/store operations. Instead, we define two new operations (better names may be needed):

* `fmp.in` - which translates to `fmt ← fmt + stack[0]`.
* `fmt.out` - which translates to `stack[0] ← fmt + stack[0]`.

Thus, when we want to read/write to/from an absolute memory address, we use loads/stores as we do now. When we want to read/write values from addresses relative to `fmt` we put the offset at the top of the stack and then execute `fmt.out`. Thus, the only overhead is one cycle for calling `fmt.out`. And similar to option 3, when a procedure needs to allocate locals in memory, it can use `fmt.in` to update the value in `fmt` by as many locals as it requires, and then reset the `fmt` right before it returns.

**Comment by grjte** [comment]
A few points that very minorly affect readability:
- at one point you have```fmt``` instead of ```fmp```
- typo in option 3 when you reset the ```fmp``` by incrementing it again

Option 4 seems very clearly better to me. It gives us the most flexibility, seems pretty clean, and the tradeoffs don't seem to be that big a deal (but maybe I'm wrong). To summarize my understanding (and make sure I haven't missed anything) - 

Benefits:
- can still access memory by absolute address - I would rather not give this up
- easy handling of read/write of local variables for complex procedures that only costs us 1 cycle per variable + 2 cycles per  procedure to alloc/dealloc (vs. possibly 2-3 mem accesses + multiple cycles per variable in Option 1, which is the only other option that preserves absolute mem pointers. So it's many times cheaper in terms of runtime)

Tradeoffs:
- 1 new register for ```fmp``` used only for load/store (so it would go unused most of the time)
- 2 new instructions (only 1 more than Option 3, or possibly the same, and I think it's much cleaner)

You've stated you don't think the dedicated register is a big deal (although it would be good to hear a bit more about why). Are there some costs I'm missing related to having the extra instructions?

**Comment by bobbinth** [comment]
If we go with option 4, we could use a nice abstraction at the assembly level to manage locas. Specifically, in addition to `mem` we can introduce `local` destination for push/pop/load/store instructions. This would work as follows:

When declaring a procedure we would need to specify how many "local" words a procedure will use. For example:
```
proc.foo.2 -> indicates that foo needs 2 local words
proc.bar.3 -> indicates that bar needs 3 local words
proc.baz   -> indicates that baz does not need any locals in memory
```

When the procedure is invoked, all relevant instructions would be executed to update `fmp` as required. And when the procedure returns, `fmp` would be reset to its value. So, the user does not need to touch `fmp` at all.

Then, to use local memory, we could have the following assembly instructions:

* `push.local.x` - where `x` is the index of the local word
* `load.local.x`
* `pop.local.x`
* `store.local.x`

**Comment by grjte** [comment]
I really like that!

**Comment by bobbinth** [comment]
> * at one point you have`fmt` instead of `fmp`
> * typo in option 3 when you reset the `fmp` by incrementing it again

Thank you! Fixed!

> You've stated you don't think the dedicated register is a big deal (although it would be good to hear a bit more about why).

I think we'll end up somewhere between 80 and 100 columns in the trace, so, adding an extra column will increase complexity by about 1% - so, not a huge deal, in my opinion.

> Are there some costs I'm missing related to having the extra instructions?

I'm trying to make keep the instruction set to 96 instructions, and we are really close to this number now. So, adding two more instructions gives us much less room to add more instructions later (I think with these two instructions we are basically at 94).

> Option 4 seems very clearly better to me. 

Yeah, the more I think about it, the more I like it. I'll let it marinade for a little more and if nothing better comes up, will create an issue to implement this in assembly and processor.

**Comment by itzmeanjan** [comment]
> If we go with option 4, we could use a nice abstraction at the assembly level to manage locas. Specifically, in addition to `mem` we can introduce `local` destination for push/pop/load/store instructions. This would work as follows:
> 
> When declaring a procedure we would need to specify how many "local" words a procedure will use. For example:
> 
> ```
> proc.foo.2 -> indicates that foo needs 2 local words
> proc.bar.3 -> indicates that bar needs 3 local words
> proc.baz   -> indicates that baz does not need any locals in memory
> ```
> 
> When the procedure is invoked, all relevant instructions would be executed to update `fmp` as required. And when the procedure returns, `fmp` would be reset to its value. So, the user does not need to touch `fmp` at all.
> 
> Then, to use local memory, we could have the following assembly instructions:
> 
>     * `push.local.x` - where `x` is the index of the local word
> 
>     * `load.local.x`
> 
>     * `pop.local.x`
> 
>     * `store.local.x`

This is good ! 

We can do static checks for correct pointer usage inside each function body and another nice thing is relative pointer arithmetic can be empowered by it, where relative memory address computation can be managed by runtime/ VM. So using this, one will write

```
proc.fn_a.2
  {push,pop,load,store}.local.{0,1}
  # local.1 can point to some memory location where fn_b wants it to point to #
   ...
end

proc.fn_b.4
  exec.fn_a
  {push,pop,load,store}.local.{0,1,2,3}
  # local.0 can point to some memory location where its caller function wants it to point to #
  ... 
end

begin
   exec.fn_b
end
```

**Comment by bobbinth** [comment]
Supersede by #84
