### ISSUE TITLE
u32 assembly parsers for shift/rotate ops fail with legal parameter value 0

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#76]
The shift and and rotation operations in the assembly parsers are enforcing parameter bounds on the bit shift value of 1 <= b <= 31, but according to the [assembly specs](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA?view#Bitwise-operations) parameter value b = 0 should be allowed.

This should be fixed in ```parse_u32shl```, ```parse_u32shr```, ```parse_u32rotl```, ```parse_u32rotr``` in the [Assembly ops parsers](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/u32_ops.rs).

**Comment by bobbinth** [comment]
Fixed by #92
