### ISSUE TITLE
Update u32 ops proptests in the processor to only test valid cases

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#79]
Given that proptest may need different sampling for valid vs. invalid inputs, it makes sense to handle these separately.

As discussed, we've decided to handle error cases in manual tests and only test validity in the randomized tests.

This should be updated in the processor u32 tests [here](https://github.com/maticnetwork/miden/blob/next/processor/src/tests/u32_ops.rs)

> Maybe invalid cases can be handled in manual tests? And the test validity of operations over valid inputs using randomized tests?

_Originally posted by @bobbinth in https://github.com/maticnetwork/miden/pull/75#discussion_r792183579_

**Comment by bobbinth** [comment]
Fixed by #89
