### ISSUE TITLE
Incorrect implementation of parse_u32div for u32div and u32div.b operations

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#94]
The implementation of ```parse_u32div``` in the [assembly u32 ops parser](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/u32_ops.rs) currently has 2 errors:

1. The parser accepts a parameter of 0 (```u32div.0```), which means that the operation fails during execution instead of during compilation.
2. The parser asserts in [handle_arithmetic_operation](https://github.com/maticnetwork/miden/blob/next/assembly/src/parsers/u32_ops.rs) that the top element after the processor's ```U32DIV``` op should be zero, which means that all divisions with non-zero remainder fail.

**Comment by bobbinth** [comment]
Fixed by #127
