### ISSUE TITLE
Make order of input arrays consistent across all test modules

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#98]
Currently, some test modules take input arrays in order while other modules require the inputs to be in the order they would be in after being pushed onto the stack, which is the reverse order.

We should make the order of input arrays consistent across all tests. Specifically, all test input arrays should be provided with data in order (not stack order), and we can update the test helper functions as required.

Changes are required in the following test modules:

All processor integration tests (not unit tests):
- [x] processor [crypto_ops tests](https://github.com/maticnetwork/miden/blob/next/processor/src/tests/crypto_ops.rs)
- [x] processor [field_ops tests](https://github.com/maticnetwork/miden/blob/next/processor/src/tests/field_ops.rs)
- [x] processor [flow_control tests](https://github.com/maticnetwork/miden/blob/next/processor/src/tests/flow_control.rs)
- [x] processor [u32 ops tests](https://github.com/maticnetwork/miden/blob/next/processor/src/tests/u32_ops.rs)

**Comment by grjte** [comment]
Looking at this a bit more - when calling ```ProgramInputs::new``` followed by ```Process::new``` the order of inputs ends up on the stack in exactly the order in which it was first passed to ```ProgramInputs::new```, which is why all integration tests are taking inputs in stack order.

This also seems to mean that users would need to provide inputs in stack order, which feels a bit counterintuitive to me. I'm not sure we should require them to think about the fact that it's a stack machine and what that means. For example, if I want to give you my first 2 fibonacci inputs, I would expect to say [0, 1] rather than [1, 0].  However, in the existing [examples](https://github.com/maticnetwork/miden/blob/main/examples/src/fibonacci.rs) and in the [docs](https://github.com/maticnetwork/miden/blob/main/miden/README.md#fibonacci-calculator) we currently show [1, 0].

What's the rationale for doing it this way? If we're going to stick with this approach, I think we need to document it carefully in the usage documentation. I also think it means that to resolve this particular issue (test input consistency) we want to do the opposite of what I proposed in the original description - instead of updating the integration tests, we would want to update the unit tests so that inputs are provided in stack order everywhere.

**Comment by bobbinth** [comment]
> What's the rationale for doing it this way?

I don't think there was a good reason for doing so (or at least, I can't come up with it now). And I agree that it would be more intuitive to provide inputs in regular order. Then, we can reverse them either in `ProgramInputs::new()` or in `Stack::new()` functions.

**Comment by grjte** [comment]
Great, sounds good to me! In that case, would you prefer that I update docs/examples (as referenced above) as part of this? Or should we leave that for the general docs/examples update pass that will come when this version is complete? (Most of the places that look like they would need updates actually seem to use ProgramInputs::from_public, which it looks like we've gotten rid of anyway, so maybe changing the scope of the updates for this task doesn't make sense)

**Comment by bobbinth** [comment]
Yes - let's leave doc updates for later. This will avoid some re-work later, I think.

**Comment by bobbinth** [comment]
Closed by #108
